language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0-preview2-003121

branches:
  only:
  - master
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1
install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/PowerShell/PowerShell/v6.0.0-alpha.16/tools/download.sh)
  - powershell -noprofile -c '$PSVersionTable'
  - sudo powershell ./tests/InfluxDB.Client.Net.TestSetup.ps1 &>/dev/null
before_script:
  - dotnet restore "./src/AdysTech.InfluxDB.Client.Net.Core/AdysTech.InfluxDB.Client.Net.Core.csproj"
  - dotnet restore "./tests/AdysTech.InfluxDB.Client.Net.Core.Test/AdysTech.InfluxDB.Client.Net.Core.Test.csproj"
script:
  - dotnet build "./src/AdysTech.InfluxDB.Client.Net.Core/AdysTech.InfluxDB.Client.Net.Core.csproj"
  - dotnet test "./tests/AdysTech.InfluxDB.Client.Net.Core.Test/AdysTech.InfluxDB.Client.Net.Core.Test.csproj"