version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- set PATH="C:\Program Files (x86)\MSBuild\14.0\Bin";%PATH%
build:
  verbosity: minimal

test_script:
- ps: >-
    $source = "https://github.com/mvadu/influxdb/releases/download/v0.11.0-rc1/Influxdb.v0.11.0-rc1.zip"

    $destination = "$env:Temp\influxdb-nightly_windows_amd64.zip"

    Invoke-WebRequest $source -OutFile $destination

    $x = 7z x $destination -o"$env:Temp\influxdb"

    Start-Process -FilePath "$env:Temp\influxdb\influxd.exe"

    pwd

    vstest.console /logger:Appveyor ".\AdysTech.InfluxDB.Client.Net.Test\bin\Debug\Tests.orderedtest"

deploy: off