version: 0.{build}
image: Visual Studio 2017 RC
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- nuget restore
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
deploy:
- provider: NuGet
  server: https://www.nuget.org/packages/AdysTech.InfluxDB.Client.Net
  api_key:
    secure: nlBDuJJE7GoAtSvHKJDjdutExvlEQErL8Q9gFqmhURY4xUgFT946cs2mLeQ2Qezi
  on:
    branch: master
before_test:
- ps: tests\InfluxDB.Client.Net.TestSetup.ps1
