version: 0.{build}
image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

before_build:
- nuget restore
- dotnet restore

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true

before_test:
- ps: tests\InfluxDB.Client.Net.TestSetup.ps1

deploy:
- provider: NuGet
  api_key:
    secure: x3I/stoKSfZBfSgc91uX34lkSU+Qs7XfgVJVSSKZsgeqKpz3WLIye9Ys6Gv7jpoo
  on:
    branch: master


artifacts:
  - path: '*.nupkg'
    name: NuGet Packages
  - path: '*.snupkg'
    name: NuGet Symbol Packages